---
- name: 'test {{ share.path }} existence'
  stat:
    path: '{{ share.path }}'
  register: path_stat

# create
- block:
  # need mkdir
  - name: mkdir/chown/chmod
    file:
      path: '{{ share.path }}'
      state: directory
      owner: '{{ share.owner | default(omit) }}'
      group: '{{ share.group | default(omit) }}'
      mode: '{{ share.mode | default(omit) }}'
      recurse: '{{ share.recurse | default(omit) }}'
  when: reshare | default(False) or not path_stat.stat.exists
