---
- name: 'test {{ share.path }} existence'
  stat:
    path: '{{ share.path }}'
  register: path_stat

# create
- block:
  # need mkdir
  - name: mkdir
    file:
      path: '{{ share.path }}'
      state: directory
  when: not path_stat.stat.exists

